### ISSUE TITLE
Can db be migrated from another instance?

### ISSUE THREAD

**Issue by uhlhosting** [fghaas/taiga-ansible#12]
Lets say i would like to redeploy Taiga, and i use this ansible playbook, what are my options to migrate old db into newly deployed machine?

**Comment by fghaas** [comment]
First up please be advised that I haven't had much bandwidth to maintain this in the last few months, so what follows is tentative and your mileage may vary. 

For migrating from an existing Taiga instance to another, you have two approaches:

* Either you take a look at [backup.yml](/fghaas/taiga-ansible/blob/master/roles/taiga-back/tasks/backup.yml) and manually build a tarball that matches what that play generates, for your source instance. That's relatively straightforward; all you'll need is a PostgreSQL database dump and the content of your `media` directory, both rolled into a bzipped tarball.

* Or you populate the variables so that the playbook can talk to your source instance, and [run the playbook with `--tags backup`](/fghaas/taiga-ansible#backups).

Either way you create your tarball, [follow the instructions for a restore](/fghaas/taiga-ansible#restore) to import your data into your target instance.
